<?php

class Neirda24AutoloadCache
{
    /**
     * Absolute path to the vendor directory of the current project.
     *
     * @var string
     */
    protected $vendorDir;

    /**
     * Neirda24AutoloadCache constructor.
     *
     * @param string $vendorDir
     */
    public function __construct($vendorDir)
    {
        $this->vendorDir = $vendorDir;
    }

    /**
     * @param string $key
     *
     * @return string
     */
    protected function generateFileNAmeFromKey($key)
    {
        return $this->vendorDir . '/composer/cache_autoload_' . $key . '.php';
    }

    /**
     * Create the file
     *
     * @param string $key
     * @param array  $values
     */
    public function save($key, array $values)
    {
        $stringArray = 'return array(';
        foreach ($values as $key => $value) {
            $stringArray .= sprintf('    "%s" => "%s",', $key, $value);
            $stringArray .= PHP_EOL;
        }
        $stringArray .= ');';

        $file = <<<EOF
<?php

// @generated by neirda24/composer-dependency-plugin

$stringArray
EOF;

        file_put_contents($this->generateFileNAmeFromKey($key), $file);
    }

    /**
     * @param string $key
     *
     * @return bool
     */
    public function exists($key)
    {
        return file_exists($this->generateFileNAmeFromKey($key));
    }
}
